# Generated by Django 5.0 on 2024-01-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplins', '0002_grades_term_alter_grades_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='name',
        ),
    ]
