# Generated by Django 4.2.7 on 2023-12-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_discipline_studygroup_user_study_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
    ]
