# Generated by Django 4.2.7 on 2023-12-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('08:30 - 10:00', '08:30 - 10:00'), ('10:10 - 11:40', '10:10 - 11:40'), ('11:50 - 13:20', '11:50 - 13:20'), ('13:30 - 15:00', '13:30 - 15:00'), ('15:10 - 16:40', '15:10 - 16:40'), ('16:50 - 18:20', '16:50 - 18:20'), ('18:30 - 20:00', '18:30 - 20:00'), ('20:10 - 21:40', '20:10 - 21:40')], max_length=20),
        ),
    ]
