# Generated by Django 5.0 on 2024-01-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduates',
            name='place_work',
            field=models.CharField(max_length=255),
        ),
    ]
