# Generated by Django 5.0 on 2024-01-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_alter_graduates_place_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduates',
            name='time',
        ),
    ]
