# Generated by Django 4.2.7 on 2023-12-17 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vkr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='group',
            new_name='groups',
        ),
        migrations.AddField(
            model_name='commission',
            name='defender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committions_defended', to=settings.AUTH_USER_MODEL),
        ),
    ]
