# Generated by Django 4.2.7 on 2023-12-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vkr', '0002_rename_group_commission_groups_commission_defender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='defender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committions_defended', to=settings.AUTH_USER_MODEL),
        ),
    ]
