# Generated by Django 4.2.7 on 2023-12-20 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vkr', '0006_thesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='reports/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
