# Generated by Django 4.2.7 on 2023-12-20 15:57

from django.db import migrations, models
import django.db.models.deletion
import vkr.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_discipline_studygroup_user_study_group'),
        ('vkr', '0007_studentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='report',
            field=models.FileField(upload_to=vkr.models.get_upload_to),
        ),
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(upload_to=vkr.models.get_upload_to)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studygroup')),
            ],
        ),
    ]
