# Generated by Django 4.2.7 on 2023-12-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0008_alter_studentreport_report_teachingmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='secretary',
        ),
    ]
